/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.softenger.stocks.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Stock service. Represents a row in the &quot;Softenger_Stock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.softenger.stocks.model.impl.StockModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.softenger.stocks.model.impl.StockImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Stock
 * @generated
 */
@ProviderType
public interface StockModel
	extends BaseModel<Stock>, GroupedModel, ShardedModel, StagedAuditedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a stock model instance should use the {@link Stock} interface instead.
	 */

	/**
	 * Returns the primary key of this stock.
	 *
	 * @return the primary key of this stock
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this stock.
	 *
	 * @param primaryKey the primary key of this stock
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this stock.
	 *
	 * @return the uuid of this stock
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this stock.
	 *
	 * @param uuid the uuid of this stock
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the stock ID of this stock.
	 *
	 * @return the stock ID of this stock
	 */
	public long getStockId();

	/**
	 * Sets the stock ID of this stock.
	 *
	 * @param stockId the stock ID of this stock
	 */
	public void setStockId(long stockId);

	/**
	 * Returns the group ID of this stock.
	 *
	 * @return the group ID of this stock
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this stock.
	 *
	 * @param groupId the group ID of this stock
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this stock.
	 *
	 * @return the company ID of this stock
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this stock.
	 *
	 * @param companyId the company ID of this stock
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this stock.
	 *
	 * @return the user ID of this stock
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this stock.
	 *
	 * @param userId the user ID of this stock
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this stock.
	 *
	 * @return the user uuid of this stock
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this stock.
	 *
	 * @param userUuid the user uuid of this stock
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this stock.
	 *
	 * @return the user name of this stock
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this stock.
	 *
	 * @param userName the user name of this stock
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this stock.
	 *
	 * @return the create date of this stock
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this stock.
	 *
	 * @param createDate the create date of this stock
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this stock.
	 *
	 * @return the modified date of this stock
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this stock.
	 *
	 * @param modifiedDate the modified date of this stock
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this stock.
	 *
	 * @return the status of this stock
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this stock.
	 *
	 * @param status the status of this stock
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this stock.
	 *
	 * @return the status by user ID of this stock
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this stock.
	 *
	 * @param statusByUserId the status by user ID of this stock
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this stock.
	 *
	 * @return the status by user uuid of this stock
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this stock.
	 *
	 * @param statusByUserUuid the status by user uuid of this stock
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this stock.
	 *
	 * @return the status by user name of this stock
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this stock.
	 *
	 * @param statusByUserName the status by user name of this stock
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this stock.
	 *
	 * @return the status date of this stock
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this stock.
	 *
	 * @param statusDate the status date of this stock
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this stock.
	 *
	 * @return the name of this stock
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this stock.
	 *
	 * @param name the name of this stock
	 */
	public void setName(String name);

	/**
	 * Returns the quantity of this stock.
	 *
	 * @return the quantity of this stock
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this stock.
	 *
	 * @param quantity the quantity of this stock
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns <code>true</code> if this stock is approved.
	 *
	 * @return <code>true</code> if this stock is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this stock is denied.
	 *
	 * @return <code>true</code> if this stock is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this stock is a draft.
	 *
	 * @return <code>true</code> if this stock is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this stock is expired.
	 *
	 * @return <code>true</code> if this stock is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this stock is inactive.
	 *
	 * @return <code>true</code> if this stock is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this stock is incomplete.
	 *
	 * @return <code>true</code> if this stock is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this stock is pending.
	 *
	 * @return <code>true</code> if this stock is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this stock is scheduled.
	 *
	 * @return <code>true</code> if this stock is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}